const $ = id => document.getElementById(id);
let subscriptions=[], matched=[], stopRequested=false, token=null, removed=0;
const OAUTH_PLACEHOLDERS=["PASTE_CHROME_EXTENSION_OAUTH_CLIENT_ID_HERE","REPLACE_WITH_CHROME_EXTENSION_OAUTH_CLIENT_ID"];
function configured(){const id=chrome.runtime.getManifest().oauth2?.client_id||"";return Boolean(id)&&!OAUTH_PLACEHOLDERS.some(marker=>id.includes(marker))}
function status(msg,bad=false){$("status").textContent=msg;$("status").style.color=bad?"#ff8a9a":""}
function counts(){$("totalCount").textContent=subscriptions.length;$("matchedCount").textContent=matched.length;$("selectedCount").textContent=document.querySelectorAll(".subcheck:checked").length;$("removedCount").textContent=removed;$("removeBtn").disabled=document.querySelectorAll(".subcheck:checked").length===0}
async function getToken(interactive=true){const r=await chrome.identity.getAuthToken({interactive});token=r?.token;if(!token)throw new Error("No OAuth token returned");$("authBadge").textContent="Connected";$("authBadge").classList.add("ok");return token}
async function api(url,options={}){if(!token)await getToken(true);const headers=new Headers(options.headers||{});headers.set("Authorization",`Bearer ${token}`);let r=await fetch(url,{...options,headers});if(r.status===401){await chrome.identity.removeCachedAuthToken({token});token=null;await getToken(true);headers.set("Authorization",`Bearer ${token}`);r=await fetch(url,{...options,headers})}return r}
async function fetchAll(){subscriptions=[];let page="";do{if(stopRequested)break;const p=new URLSearchParams({part:"snippet",mine:"true",maxResults:"50"});if(page)p.set("pageToken",page);const r=await api(`https://www.googleapis.com/youtube/v3/subscriptions?${p}`);const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||`YouTube API ${r.status}`);subscriptions.push(...(b.items||[]));page=b.nextPageToken||"";status(`Scanning… ${subscriptions.length} subscriptions loaded`)}while(page)}
function filter(){const before=$("beforeDate").value?new Date(`${$("beforeDate").value}T00:00:00Z`):null;const after=$("afterDate").value?new Date(`${$("afterDate").value}T00:00:00Z`):null;const name=$("nameFilter").value.trim().toLowerCase();matched=subscriptions.filter(item=>{const s=item.snippet||{},d=new Date(s.publishedAt);if(before&&!(d<before))return false;if(after&&!(d>=after))return false;if(name&&!(s.title||"").toLowerCase().includes(name))return false;return true}).sort((a,b)=>new Date(a.snippet.publishedAt)-new Date(b.snippet.publishedAt))}
function render(){const list=$("list");list.innerHTML="";if(!matched.length){list.innerHTML='<div class="empty">No subscriptions matched your filters.</div>';counts();return}const frag=document.createDocumentFragment();matched.forEach((item,index)=>{const row=document.createElement("label");row.className="item";const date=new Date(item.snippet.publishedAt).toISOString().slice(0,10);row.innerHTML=`<input class="subcheck" type="checkbox" data-index="${index}" checked><div><div class="title"></div><div class="meta"></div></div><div class="date">${date}</div>`;row.querySelector(".title").textContent=item.snippet.title||"Unknown channel";row.querySelector(".meta").textContent=item.snippet.resourceId?.channelId||"";frag.appendChild(row)});list.appendChild(frag);list.querySelectorAll(".subcheck").forEach(cb=>cb.addEventListener("change",counts));counts()}
$("connectBtn").addEventListener("click",async()=>{if(!configured()){$("setupPanel").classList.remove("hidden");status("Production OAuth client is not bound yet.",true);return}try{status("Opening Google authorization…");await getToken(true);status("YouTube connected.")}catch(e){status(`Connect failed: ${e.message}`,true)}});
$("disconnectBtn").addEventListener("click",async()=>{try{if(token)await chrome.identity.removeCachedAuthToken({token});await chrome.identity.clearAllCachedAuthTokens();token=null;$("authBadge").textContent="Not connected";$("authBadge").classList.remove("ok");status("Disconnected.")}catch(e){status(e.message,true)}});
$("scanBtn").addEventListener("click",async()=>{if(!configured()){$("setupPanel").classList.remove("hidden");status("Production OAuth client is not bound yet.",true);return}try{stopRequested=false;$("stopBtn").disabled=false;$("scanBtn").disabled=true;status("Connecting and scanning…");await getToken(true);await fetchAll();filter();render();status(`Scan complete: ${matched.length} matched of ${subscriptions.length}.`)}catch(e){status(`Scan failed: ${e.message}`,true)}finally{$("scanBtn").disabled=false;$("stopBtn").disabled=true}});
$("stopBtn").addEventListener("click",()=>{stopRequested=true;status("Stopping after the current request…")});
$("selectAllBtn").addEventListener("click",()=>{document.querySelectorAll(".subcheck").forEach(cb=>cb.checked=true);counts()});
$("clearBtn").addEventListener("click",()=>{document.querySelectorAll(".subcheck").forEach(cb=>cb.checked=false);counts()});
$("removeBtn").addEventListener("click",async()=>{const selected=[...document.querySelectorAll(".subcheck:checked")].map(cb=>matched[Number(cb.dataset.index)]).filter(Boolean);if(!selected.length)return;if(!confirm(`Really unsubscribe from ${selected.length} selected YouTube channels?`))return;stopRequested=false;removed=0;$("removeBtn").disabled=true;$("stopBtn").disabled=false;$("progress").max=selected.length;$("progress").value=0;for(let i=0;i<selected.length;i++){if(stopRequested)break;const item=selected[i],name=item.snippet?.title||"Unknown";status(`Unsubscribing ${i+1}/${selected.length}: ${name}`);const p=new URLSearchParams({id:item.id});const r=await api(`https://www.googleapis.com/youtube/v3/subscriptions?${p}`,{method:"DELETE"});if(r.ok||r.status===204){removed++;matched=matched.filter(x=>x.id!==item.id);subscriptions=subscriptions.filter(x=>x.id!==item.id)}else{let message=`YouTube API ${r.status}`;try{const b=await r.json();message=b?.error?.message||message;const reason=b?.error?.errors?.[0]?.reason||"";if(reason.includes("quota")||message.toLowerCase().includes("quota")){status(`Quota reached after ${removed} removals. Already removed channels stay removed.`,true);break}}catch{}status(`Failed on ${name}: ${message}`,true)}$("progress").value=i+1;counts();await new Promise(r=>setTimeout(r,250))}render();$("stopBtn").disabled=true;counts();if(!stopRequested)status(`Done. Removed ${removed} channel(s).`)});
document.addEventListener("DOMContentLoaded",async()=>{if(!configured())$("setupPanel").classList.remove("hidden");const saved=await chrome.storage.local.get(["afterDate","beforeDate","nameFilter"]);if(saved.afterDate)$("afterDate").value=saved.afterDate;if(saved.beforeDate)$("beforeDate").value=saved.beforeDate;if(saved.nameFilter)$("nameFilter").value=saved.nameFilter;for(const id of ["afterDate","beforeDate","nameFilter"]){$(id).addEventListener("change",async()=>chrome.storage.local.set({[id]:$(id).value}))}if(configured()){try{await getToken(false);status("YouTube token available.")}catch{status("Ready. Click Connect YouTube.")}}});